@startuml
'https://plantuml.com/component-diagram

package "client" {
[AccountClient]
}

package "Dto" {
  [FundsTransferResponseDto]
  [FundsTransferRequestDto]
}

package "Controller" {
  [FundsTransferController]
}

package "repository" {
  [FundsTransferRepository]
}

package "Service" {
  [FundsTransferService]
}

package "Scheduler" as Scheduler {
    [pendingRequests]
    [stalledRequests]
}

database "FundsTransferRequestDB" {
  folder "transferRequest" as transferRequest {
    [transferRequest 1, 2, ..]
  }
}

Http --> [FundsTransferController]

[FundsTransferController] --> [FundsTransferRequestDto]

[FundsTransferController] -> [FundsTransferService] : createFundsTransferRequest

[FundsTransferService] -> [FundsTransferRepository]

[FundsTransferRepository] -> transferRequest

[pendingRequests] --> [AccountClient] : update the\n request status
[stalledRequests] --> [AccountClient] : update the\n request status

Scheduler -> transferRequest

[AccountClient] -> account_service : HTTP POST

@enduml
